cache: apt
language: cpp
compiler:
  - clang
before_install:
# Turn off local DBI Services started by default (contributes to OOM on weaker machines).
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
# Create an additional nice little swap file, since Travis has no defined limit on Disk Space.
  - dd if=/dev/zero of=local.swap bs=1M count=4096
  - chmod 600 local.swap
  - sudo mkswap local.swap
  - sudo chown root:root local.swap
  - sudo swapon local.swap
  - ulimit -a
  - ps aux
# Add external repositories and do system updates
  - sudo apt-get update -qq
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee --append /etc/apt/sources.list
  - echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee --append /etc/apt/sources.list
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev clang-3.5
  - sudo apt-get update -qq
before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build && cd build
  - CC=clang-3.5 CXX=clang-3.5 python ../configure.py --enable-optimize --sdks=episode1,tf2,l4d2,csgo,dota
  - ambuild