cache: apt
language: c
compiler:
  - clang
before_install:
# Turn off local DBI services started by default (contributes to OOM on weaker machines).
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get remove consolekit
# Add external repositories and do system updates
  - sudo apt-get update -qq
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee --append /etc/apt/sources.list
  - echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee --append /etc/apt/sources.list
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev clang-3.5
  - sudo apt-get update -qq
  - sudo apt-get clean
  - sudo apt-get autoremove
before_script:
# Clean up RamFS mount.
  - sudo rm -Rf /var/ramfs/*
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

# Acquire MySQL
  - wget http://cdn.mysql.com/archives/mysql-5.6/mysql-5.6.15-linux-glibc2.5-i686.tar.gz
  - tar xzf mysql-5.6.15-linux-glibc2.5-i686.tar.gz
  - mv mysql-5.6.15-linux-glibc2.5-i686 mysql-5.5
  - rm mysql-5.6.15-linux-glibc2.5-i686.tar.gz

# MM:S
  - git clone "https://github.com/alliedmodders/metamod-source" -b 1.10-dev mmsource-1.10

# HL2SDKs
  - git clone --mirror "https://github.com/alliedmodders/hl2sdk" hl2sdk-proxy-repo
  - git clone --shared --mirror hl2sdk-proxy-repo -b episode1 hl2sdk-episode1
  - git clone --shared --mirror hl2sdk-proxy-repo -b tf2 hl2sdk-tf2
  - ls -laR hl2sdk-tf2
  - git clone --shared --mirror hl2sdk-proxy-repo -b l4d2 hl2sdk-l4d2
  - free -m
  - git clone --shared --mirror hl2sdk-proxy-repo -b csgo hl2sdk-csgo
  - git clone --shared --mirror hl2sdk-proxy-repo -b dota hl2sdk-dota
  - free -m

# AMBuild
  - git clone "https://github.com/alliedmodders/ambuild"
  - cd ambuild
  - python setup.py build
  - sudo python setup.py install
  - cd ..

script:
  - mkdir build && cd build
  - CC=clang-3.5 CXX=clang-3.5 python ../configure.py --enable-optimize --sdks=episode1,tf2,l4d2,csgo,dota
  - ambuild